### PR TITLE
OOP on Species

### PR DESCRIPTION
**Pull request by TNDMedeiros**
I started  the OOP , in order to show the species' Nomenclature and the Authoring of the first description. Feel free to **edit the file**, **upgrade the Class** and **work on the function!**

### CODE REVIEW

**Comment by peixespnsc** [comment]
**Observations on getNomenclature**

- $sql >> there's no need to use “ORDER BY id”. Because or this will be a function parameter, or will be a Specie single page. Also, if needed, you forget to refer it as “sp.id”
- mysqli_fetch_assoc >> let's use “mysqli_fetch_object” and chage $row['field'] to $row->field

$row['dubious'] (see “modules/taxa_tree.php”)
- use a switch ($row->dubious)
- don't put $row->genus and $row->specie inside the switch, you are being redundant
- always use the abbreviation within the HTML TAG <abbr>
- - affinis isn't a abbreviation, it's aff. or affin. Let's use aff.
- - sp. must come between genus and species, like you did in aff. and cf. Look at these cases:
- - - Rineloricaria sp. n. >> “n.” is the specie field
- - - Characidium sp. 1 >> “1” is the specie field
- on the final step, concat $row->genus, $dubious and $row->specie, all inside a HTML TAG <em> (emphasys, to make it italic, as all nomenclature should be written)

**Comment by TNMedeiros** [comment]
@peixespnsc I uploaded a new file with some changes!

**Comment by peixespnsc** [comment]
Great!
Now we need an ID as a function parameter, and a "WHERE" clase in the $sql.
And at the end of the function put a "return $nomenclature".

**Comment by peixespnsc** [comment]
**Observations on getTaxonomists()**

- Let's call it getAuthoring()? Cause we are getting more than Taxonomists here
- $sql >> like in getNomenclature(), we don't need “sp.id” here, but we need $id as a function parameter. Also, the “WHERE” clause needs only the $id
- mysqli_fetch_assoc >> let's use “mysqli_fetch_object” and chage $row['field'] to $row->field 
- You are being redundant when you repeat the lines below
- - $last = array_pop ($taxonomist);
- - $firsts = implode (',', $taxonomist); >> remember to put a “space” after comma
- - $taxonomist = sprintf ('%s & %s', $firsts, $last);
- You are also being redundant when you check $count and $revised 4 times
- Create $authoring to concat $taxonomists and $row->year, then check if it's revised
- And at the end of the function put a "return $authoring"

**Comment by TNMedeiros** [comment]
@peixespnsc , I just made some adjustments and a new function called "getSynonyms". Check it out! Thanks.

**Comment by peixespnsc** [comment]
Too many conflicts, I'll update the master branch

**Pull request closed without merging**
